ENV = "development"
DB = "allofus"
DBURL = "mongodb://localhost:27017/allofus"
PORT = "3500"
LogDir = "./logs"
JWTSecret = "secret"
S3Region = "us-east-2"
S3Bucket = "www.all-of.us"
AWSAccessKeyId = "AKIAJW7S5A26Y7SQ2QHQ"
AWSSecretKey = "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"