ENV = "development"
DB = "heroku_ldh3hrks"
DBURL = "mongodb://allofusapi:84P8wnwaiy8uAvJ@ds225624.mlab.com:25624/heroku_ldh3hrks"
PORT = "5000"
LogDir = "./logs"
JWTSecret = "secret"
S3Region = "us-east-2"
S3Bucket = "www.all-of.us"
AWSAccessKeyId = "AKIAJW7S5A26Y7SQ2QHQ"
AWSSecretKey = "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"