env:
  browser: true
  es6: true
extends:
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
rules:
  strict:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - varsIgnorePattern: 'm'
